name: Deploy Client

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Build React app
        run: npm run build
        working-directory: ./client

      - name: Copy build files to repository root
        run: |
          cp -r $GITHUB_WORKSPACE/client/build/* $GITHUB_WORKSPACE

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
